spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: pablo.garciasimavilla@gmail.com
    password: npvhvicjbofirwtq
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
  application:
    security:
      jwt:
        secret-key: s1e2c3r4e5t6k7e8y9s1e2c3r4e5t6k7e8y9s1e2c3r4e5t6k7e8y9s1e2c3r4e5t6k7e8y9s1e2c3r4e5t6k7e8y9
        expiration: 86400000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    file:
      uploads:
        photos-output-path: ./uploads
server:
  port: 8088
